/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/purchases": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get All Purchase Endpoint */
		get: operations["get_all_purchase_endpoint_purchases_get"];
		put?: never;
		/** Create Purchase Endpoint */
		post: operations["create_purchase_endpoint_purchases_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * PurchaseCreateRequest
		 * @description 購入物の新規作成リクエスト。
		 */
		PurchaseCreateRequest: {
			/** Name */
			name: string;
			/** Category */
			category: string;
			/**
			 * Speed
			 * @description 消費スピード
			 */
			speed: number;
			/**
			 * Stock
			 * @description 現在の在庫
			 */
			stock: number;
			/**
			 * Is Temporary
			 * @default false
			 */
			is_temporary: boolean;
		};
		/**
		 * PurchaseResponse
		 * @description 購入物のレスポンス表現。
		 */
		PurchaseResponse: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/** Category */
			category: string;
			/** Speed */
			speed: number;
			/** Stock */
			stock: number;
			/** Is Temporary */
			is_temporary: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_all_purchase_endpoint_purchases_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PurchaseResponse"][];
				};
			};
		};
	};
	create_purchase_endpoint_purchases_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PurchaseCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PurchaseResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
